# The config for development
production: false
timezone: "America/New_York"

    ###### ANYTHING BELOW THIS GOES TO PRODUCTION ######
# copy #

name: Gastrograph's Gastronexus blog
title: Gastrograph
description: All up in your flavor space
email: evandev@gastrograph.com
baseurl: ""
url: "http://www.gastrograph.com"
destination: _site/

# Build settings
#markdown: kramdown
highlighter: pygments
permalink: none
excerpt_separator: <!--more-->
paginate: 5

exclude:
  - 'bower_components'
  - 'node_modules'
  - 'bower.json'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Gruntfile.js'
  - 'package.json'
  - 'Rakefile'
  - 's3_website.yml'
  - 'production.yml'

gems:
    - jekyll-redirect-from
    - jekyll-minimagick
    - octopress-debugger

markdown: redcarpet
redcarpet:
    extensions: ["strikethrough", "tables"]

# author pages
author_dir: blogs/authors
picture:
  source: assets/images
  output: generated
  markup: picture
  presets:
    post-images:
      ppi: [1]
      attr:
        class: blog-full
        itemprop: image
      source_lg:
        media: "(min-width: 40em)"
        width: 700
      source_md:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 130
    blog_links:
      attr:
        class: blog-links
        itemprop: image
      source_lg:
        media: "(min-width: 40em)"
        width: 200
      source_default:
        width: 100
image:
  source: assets/images
  ouput: generated
  presets:
    post-images:
      attr:
        class: center-block img-responsive

mini_magick:
  whitepaper-link:
    source: assets/images/post-images
    destination: assets/images/post-link
    resize: 'x600'
    crop: "400x695+100+0"

### Subscribe Wall
subscribe_wall:
  layouts:
###pages:
####- "/resources/index.html"


pdf:
  pages:
    - "/learn/how-to-review.html"

### sitemap
sitemap:
    exclude:
    include_posts:
        - "/index.html"
        - "/about.html"
        - "/science.html"
        - "/pricing.html"
        - "/learn.html"
        - "/jobs.html"
        - "/privacy.html"
        - "/blogs/index.html"
        - "/blogs/authors/*/index.html"
        - "/blogs/dev/index.html"
        - "/blogs/gastronexus/index.html"
        - "/blogs/dev/index.html"
